---
driver:
  name: vagrant
  pre_create_command: "cd {{vagrant_root}}/ && vagrant box update"

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

platforms:
  - name: gannett/gci-centos7

suites:
- name: default
  run_list:
  - recipe[python]
  - recipe[virtualenv-test]
  attributes:
    python:
      setuptools_version: 18.0.1
      virtualenv_version: 13.1.0
- name: chef14-default
  provisioner:
    require_chef_omnibus: 14.0.202
  run_list:
  - recipe[python]
  - recipe[virtualenv-test]
  attributes:
    python:
      setuptools_version: 18.0.1
      virtualenv_version: 13.1.0
- name: package
  run_list:
  - recipe[python]
  - recipe[virtualenv-test]
  attributes:
    python:
      install_method: "package"
      setuptools_version: 18.0.1
      virtualenv_version: 13.1.0
- name: custom-package
  run_list:
  - recipe[python]
  - recipe[virtualenv-test]
  attributes:
    python:
      install_method: "custom-package"
      setuptools_version: 18.0.1
      virtualenv_version: 13.1.0
- name: source
  run_list:
  - recipe[python]
  - recipe[virtualenv-test]
  attributes:
    python:
      install_method: "source"
      setuptools_version: 18.0.1
      virtualenv_version: 13.1.0
