---
driver:
  name: vagrant
  customize:
      memory: 2048

provisioner:
  name: chef_zero
  chef_zero_port: 9010

platforms:
- name: centos-6.6
  driver_config:
    box: opscode-centos-6.6
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.6_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[yum-gd]
  - recipe[python]
  attributes:
    python:
      setuptools_version: 18.0.1
      virtualenv_version: 13.1.0
- name: package
  run_list:
  - recipe[yum-gd]
  - recipe[python]
  attributes:
    python:
      install_method: "package"
      setuptools_version: 18.0.1
      virtualenv_version: 13.1.0
- name: source
  run_list:
  - recipe[yum-gd]
  - recipe[python]
  attributes:
    python:
      install_method: "source"
      setuptools_version: 18.0.1
      virtualenv_version: 13.1.0